# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\xc-F\Documents\Programer\python\PPGOMS\src\ui\serial.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 786)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("font: 25 10pt \"Microsoft YaHei\";\n"
"background-color: rgb(240, 255, 248);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser_receive = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_receive.setStyleSheet("background-color: rgb(226, 255, 239);\n"
"font: 25 12pt \"Microsoft YaHei\";")
        self.textBrowser_receive.setObjectName("textBrowser_receive")
        self.horizontalLayout.addWidget(self.textBrowser_receive)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(240, 261))
        self.groupBox.setObjectName("groupBox")
        self.label_status = QtWidgets.QLabel(self.groupBox)
        self.label_status.setGeometry(QtCore.QRect(182, 40, 26, 26))
        self.label_status.setStyleSheet("#label_status{\n"
"    border-radius: 13px;\n"
"    background-color:gray ;\n"
"}\n"
"#label_status[isOn=\"true\"]{\n"
"background-color: green;\n"
"}")
        self.label_status.setText("")
        self.label_status.setProperty("isOn", False)
        self.label_status.setObjectName("label_status")
        self.pushButton_connect = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_connect.setGeometry(QtCore.QRect(76, 40, 92, 28))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.pushButton_flush = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_flush.setGeometry(QtCore.QRect(20, 40, 45, 28))
        self.pushButton_flush.setObjectName("pushButton_flush")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 87, 228, 165))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_port = QtWidgets.QLabel(self.layoutWidget)
        self.label_port.setAlignment(QtCore.Qt.AlignCenter)
        self.label_port.setObjectName("label_port")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.comboBox_port = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_port.setObjectName("comboBox_port")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_port)
        self.label_baud = QtWidgets.QLabel(self.layoutWidget)
        self.label_baud.setAlignment(QtCore.Qt.AlignCenter)
        self.label_baud.setObjectName("label_baud")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_baud)
        self.comboBox_baud = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_baud)
        self.label_parity = QtWidgets.QLabel(self.layoutWidget)
        self.label_parity.setAlignment(QtCore.Qt.AlignCenter)
        self.label_parity.setObjectName("label_parity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_parity)
        self.comboBox_parity = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_parity)
        self.label_data = QtWidgets.QLabel(self.layoutWidget)
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName("label_data")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_data)
        self.comboBox_data = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_data.setObjectName("comboBox_data")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_data)
        self.label_stop = QtWidgets.QLabel(self.layoutWidget)
        self.label_stop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stop.setObjectName("label_stop")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_stop)
        self.comboBox_stop = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_stop.setObjectName("comboBox_stop")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_stop)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(240, 197))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(24, 108, 195, 77))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_clear_receive = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_clear_receive.setObjectName("pushButton_clear_receive")
        self.horizontalLayout_4.addWidget(self.pushButton_clear_receive)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(22, 6, 177, 95))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_hexview = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_hexview.setObjectName("radioButton_hexview")
        self.horizontalLayout_2.addWidget(self.radioButton_hexview)
        self.radioButton_asciiview = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_asciiview.setEnabled(True)
        self.radioButton_asciiview.setChecked(True)
        self.radioButton_asciiview.setObjectName("radioButton_asciiview")
        self.horizontalLayout_2.addWidget(self.radioButton_asciiview)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.checkBox_show_current_time = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_show_current_time.setObjectName("checkBox_show_current_time")
        self.verticalLayout_2.addWidget(self.checkBox_show_current_time)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plainTextEdit_send = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_send.setStyleSheet("background-color: rgb(215, 237, 255);")
        self.plainTextEdit_send.setObjectName("plainTextEdit_send")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_send)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(240, 175))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(24, 14, 195, 141))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_send = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_6.addWidget(self.pushButton_send)
        self.pushButton_clear_send = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_clear_send.setObjectName("pushButton_clear_send")
        self.horizontalLayout_6.addWidget(self.pushButton_clear_send)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_hexsend = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_hexsend.setObjectName("radioButton_hexsend")
        self.horizontalLayout_7.addWidget(self.radioButton_hexsend)
        self.radioButton_asciisend = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_asciisend.setChecked(True)
        self.radioButton_asciisend.setObjectName("radioButton_asciisend")
        self.horizontalLayout_7.addWidget(self.radioButton_asciisend)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.groupBox_5, 2, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.horizontalLayout_8.addWidget(self.lineEdit_filename)
        self.pushButton_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.horizontalLayout_8.addWidget(self.pushButton_open_file)
        self.pushButton_send_file = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_send_file.setObjectName("pushButton_send_file")
        self.horizontalLayout_8.addWidget(self.pushButton_send_file)
        self.gridLayout.addLayout(self.horizontalLayout_8, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_start = QtWidgets.QAction(MainWindow)
        self.action_start.setObjectName("action_start")
        self.action_pause = QtWidgets.QAction(MainWindow)
        self.action_pause.setObjectName("action_pause")
        self.action_reset = QtWidgets.QAction(MainWindow)
        self.action_reset.setObjectName("action_reset")
        self.action_stop = QtWidgets.QAction(MainWindow)
        self.action_stop.setObjectName("action_stop")
        self.toolBar.addAction(self.action_start)
        self.toolBar.addAction(self.action_pause)
        self.toolBar.addAction(self.action_reset)
        self.toolBar.addAction(self.action_stop)

        self.retranslateUi(MainWindow)
        self.comboBox_baud.setCurrentIndex(2)
        self.comboBox_data.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收区"))
        self.textBrowser_receive.setPlaceholderText(_translate("MainWindow", "数据接收区"))
        self.groupBox.setTitle(_translate("MainWindow", "串口"))
        self.pushButton_connect.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_flush.setText(_translate("MainWindow", "刷新"))
        self.label_port.setText(_translate("MainWindow", "端  口"))
        self.label_baud.setText(_translate("MainWindow", "波特率"))
        self.comboBox_baud.setCurrentText(_translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "1200"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "2400"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(3, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(4, _translate("MainWindow", "12400"))
        self.comboBox_baud.setItemText(5, _translate("MainWindow", "19200"))
        self.comboBox_baud.setItemText(6, _translate("MainWindow", "38400"))
        self.comboBox_baud.setItemText(7, _translate("MainWindow", "57600"))
        self.label_parity.setText(_translate("MainWindow", "校验位"))
        self.comboBox_parity.setItemText(0, _translate("MainWindow", "No"))
        self.comboBox_parity.setItemText(1, _translate("MainWindow", "Even"))
        self.comboBox_parity.setItemText(2, _translate("MainWindow", "Odd"))
        self.comboBox_parity.setItemText(3, _translate("MainWindow", "Space"))
        self.comboBox_parity.setItemText(4, _translate("MainWindow", "Mark"))
        self.comboBox_parity.setItemText(5, _translate("MainWindow", "Unknown"))
        self.label_data.setText(_translate("MainWindow", "数据位"))
        self.comboBox_data.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_data.setItemText(1, _translate("MainWindow", "6"))
        self.comboBox_data.setItemText(2, _translate("MainWindow", "7"))
        self.comboBox_data.setItemText(3, _translate("MainWindow", "8"))
        self.label_stop.setText(_translate("MainWindow", "停止位"))
        self.comboBox_stop.setItemText(0, _translate("MainWindow", "OneStop"))
        self.comboBox_stop.setItemText(1, _translate("MainWindow", "OneAndHalfStop"))
        self.comboBox_stop.setItemText(2, _translate("MainWindow", "TwoStop"))
        self.comboBox_stop.setItemText(3, _translate("MainWindow", "UnKnownStopBits"))
        self.pushButton_2.setText(_translate("MainWindow", "保存窗口"))
        self.pushButton_clear_receive.setText(_translate("MainWindow", "清除接收"))
        self.pushButton_9.setText(_translate("MainWindow", "暂停"))
        self.pushButton_10.setText(_translate("MainWindow", "停止"))
        self.label.setText(_translate("MainWindow", "接收区显示状态"))
        self.radioButton_hexview.setText(_translate("MainWindow", "HEX"))
        self.radioButton_asciiview.setText(_translate("MainWindow", "ASCII"))
        self.checkBox_show_current_time.setText(_translate("MainWindow", "时间戳"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送区"))
        self.plainTextEdit_send.setPlaceholderText(_translate("MainWindow", "数据发送区"))
        self.pushButton_send.setText(_translate("MainWindow", "发送"))
        self.pushButton_clear_send.setText(_translate("MainWindow", "清除发送"))
        self.pushButton_8.setText(_translate("MainWindow", "停止发送"))
        self.label_2.setText(_translate("MainWindow", "发送区状态"))
        self.radioButton_hexsend.setText(_translate("MainWindow", "HEX"))
        self.radioButton_asciisend.setText(_translate("MainWindow", "ASCII"))
        self.pushButton_open_file.setText(_translate("MainWindow", "打开文件"))
        self.pushButton_send_file.setText(_translate("MainWindow", "发送文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_start.setText(_translate("MainWindow", "开始"))
        self.action_start.setToolTip(_translate("MainWindow", "开始"))
        self.action_pause.setText(_translate("MainWindow", "暂停"))
        self.action_pause.setToolTip(_translate("MainWindow", "暂停"))
        self.action_reset.setText(_translate("MainWindow", "重置"))
        self.action_reset.setToolTip(_translate("MainWindow", "重置"))
        self.action_stop.setText(_translate("MainWindow", "停止"))
        self.action_stop.setToolTip(_translate("MainWindow", "停止"))

